### ISSUE TITLE
FirefoxAutoconfig.pkg.recipe - creating a custom recipe

### ISSUE THREAD

**Issue by blackberryhell** [autopkg/gregneagle-recipes#2]
Hi

Forgive me if this has already been covered but I noticed the following with the FirefoxAutoconfig.pkg.recipe

In order to create different versions of Firefox for different parts of the org we create several different versions of the CCK2 file, this generates the autoconfig.zip file. What I initially did was rename these autoconfig_lib.zip etc and then point my additional version of FirefoxAutoconfig.pkg.recipe at this file. What I noticed was that regardless of what version of the autoconfig file the recipe was pointed at it used the first one it came to, in order for the recipe to differentiate I had to change the autoconfig file name to something completely different for example Library.zip and point the recipe at it. Once I did this the recipe executed perfectly.

Anyone else seen this?

BlackberryHell

**Comment by gregneagle** [comment]
I'm not understanding what you are trying to communicate. Perhaps try again, but add some directory listings and snippets of -vv output from an atuopkg run that demonstrates the issue?

You want to describe/explain your issue such that someone else can replicate it, step by step.

**Comment by blackberryhell** [comment]
No worries

**Comment by blackberryhell** [comment]
Hi Greg

Sorry for the delay I will try and explain the issue I am seeing. So I am
using FirefoxAutoconfig.pkg.recipe to create a custom version of firefox. I
need two additional versions with different settings so I copied
the FirefoxAutoconfig.pkg.recipe and created two additional recipes that
point at two different autoconfig files.

FirefoxAutoconfig-Lib.pkg.recipe
FirefoxAutoconfig-TKS.pkg.recipe

I created two additional autoconfig.zip file for these

lib.zip
tks.zip

along with the one for generic

autoconfig_generic.zip

The issue I am seeing is that not matter which recipe I execute it is
always the first recipe alphabetically that is executed, in my case this is
FirefoxAutoconfig-Lib.pkg.recipe, the only way round this I have found is
to move the other two recipes out of the Mozilla directory.

I have attached the receipt for one failed build attempt.

Regards

Alex

**Comment by gregneagle** [comment]
Your copies almost certainly all have the same Identifiers as the original. Instead of making _copies_ you should almost certainly be making _overrides_.

https://github.com/autopkg/autopkg/wiki/Recipe-Overrides

`autopkg make-override FirefoxAutoconfig.pkg.recipe -n FirefoxAutoconfig-Lib.pkg.recipe`
`autopkg make-override FirefoxAutoconfig.pkg.recipe -n FirefoxAutoconfig-TKS.pkg.recipe`
`autopkg make-override FirefoxAutoconfig.pkg.recipe -n FirefoxAutoconfig-Generic.pkg.recipe`

and then editing the Input arrays of the resulting overrides. `make-override` should automatically give them all unique Identifiers.

Alternately, you could edit your copies and give them unique Identifiers, but I really recommend using overrides. This also has the effect of keeping your own customized recipes separate from the recipe repos maintained by others.

**Comment by gregneagle** [comment]
Note also that the autoconfig zip files should then be moved to the same directory as the recipe override.

**Comment by blackberryhell** [comment]
Cheers Greg, I will give that ago.

**Comment by blackberryhell** [comment]
Hi Greg

Sorry for using an old thread but didn't want to post in the wrong place
again, I was wondering if JAMF's quickadd should work with bootstrappr, I
have been getting an installation failure message unfortunately, is there
something I should be doing to prep the pkg?

As always thanks for making the toys to make our lives easier.

Alex

**Comment by gregneagle** [comment]
I don’t know anything about Jamf’a QuickAdd package.

**Comment by gregneagle** [comment]
Closing this old issue.
